flutter_analyze:
	flutter analyze

integration_test:
	flutter test integration_test/app_test.dart

test_driver:
	flutter drive \
      --driver=test_driver/integration_test.dart \
      --target=integration_test/app_test.dart